#
# Makefile:
#
CC	    	:= g++

STENOSYS	:= stenosys
DICTBUILD	:= dictbuild

SRCDIR		:= ./src
INCDIR		:= ./src
OBJDIR		:= ./obj
LOGDIR	    := ./log
EXEDIR		:= ./bin
DICTDIR		:= ./dictionary

SRCEXT		:= cpp
OBJEXT		:= o

INC			:= -I/usr/include
DICTIONARY	:= $(DICTDIR)/yttyx-dict.tsv
DICTHASHED	:= $(SRCDIR)/dictionary_i.cpp

# -O0       No optimisation
# -Wall		All warnings

# Use "make OUTPUT=X11" to build with X11 support
#     "make" alone builds for Pro Micro output (steno-in-the-middle)
ifeq ($(strip $(OUTPUT)),)
	CFLAGS		:= -O0 -Wall $(INCLUDE) -pipe
	LDLIBS  	:= -L/usr/lib -L/usr/local/lib -lpthread -lconfig++ -lm
else
	CFLAGS		:= -O0 -Wall $(INCLUDE) -pipe -D X11
	LDLIBS  	:= -L/usr/lib -L/usr/local/lib -lpthread -lconfig++ -lm -lX11 -lXtst
endif

# Note: dictionary_i.cpp is generated by running dictbuild
STENOSYS_SOURCES := \
	cmdparser.cpp \
	cmdparserstate.cpp \
	config.cpp \
	distribution.cpp \
	formatter.cpp \
	geminipr.cpp \
	kbdraw.cpp \
	kbdsteno.cpp \
	keyboard.cpp \
	log.cpp \
	miscellaneous.cpp \
	promicrooutput.cpp \
	serial.cpp \
	state.cpp \
	stenokeyboard.cpp \
	stenosys.cpp \
	stroke.cpp \
	strokefeed.cpp \
	strokes.cpp \
	symbols.cpp \
	textfile.cpp \
	translator.cpp \
	utf8.cpp \
	x11output.cpp

# Precede each source file with the source directory
STENOSYS_SOURCES_DIR := $(patsubst %,$(SRCDIR)/%,$(STENOSYS_SOURCES))
# Create a list of object files with their paths
STENOSYS_OBJECTS := $(patsubst $(SRCDIR)/%,$(OBJDIR)/%,$(STENOSYS_SOURCES_DIR:.$(SRCEXT)=.$(OBJEXT)))

DICTBUILD_SOURCES := \
	cmdparser.cpp \
	cmdparserstate.cpp \
	dictbuild.cpp \
	dictionary.cpp \
	distribution.cpp \
	log.cpp \
	miscellaneous.cpp \
	state.cpp \
	symbols.cpp \
	textfile.cpp \
	utf8.cpp

# Precede each source file with the source directory
DICTBUILD_SOURCES_DIR := $(patsubst %,$(SRCDIR)/%,$(DICTBUILD_SOURCES))
# Create a list of object files with their paths
DICTBUILD_OBJECTS := $(patsubst $(SRCDIR)/%,$(OBJDIR)/%,$(DICTBUILD_SOURCES_DIR:.$(SRCEXT)=.$(OBJEXT)))

.DEFAULT_GOAL := $(STENOSYS)

# Make the directories
directories:
	@mkdir -p $(EXEDIR)
	@mkdir -p $(OBJDIR)
	@mkdir -p $(LOGDIR)

# Clean only object files
clean:
	@$(RM) -rf $(OBJDIR)
	@$(RM) -rf $(EXEDIR)
	@$(RM) -rf $(LOGDIR)

#$(DICTBUILD):	$(DICTIONARY)

# Link
$(DICTBUILD):	$(DICTBUILD_OBJECTS)
	@echo [link]
	@mkdir -p $(SRCDIR)
	$(CC) -o $(EXEDIR)/$(DICTBUILD) $^ $(LDLIBS)

# Build the dictionary hash table for steno lookup
$(DICTHASHED):	$(DICTBUILD) $(DICTIONARY)
	@$(EXEDIR)/dictbuild

$(STENOSYS):	$(STENOSYS_OBJECTS)
	@echo [link]
	@mkdir -p $(EXEDIR)
	$(CC) -o $(EXEDIR)/$(STENOSYS) $^ $(LDLIBS)

# Compile
$(OBJDIR)/%.$(OBJEXT):	$(SRCDIR)/%.$(SRCEXT)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(INC) -c -o $@ $<

all:	$(DICTBUILD) $(STENOSYS)
	@echo ${X11}
